#!/bin/bash
nvcc="/usr/local/cuda/bin/nvcc"
args=(-arch sm_21 -ccbin g++-4.8)
ccargs=""
#verbosity=1
forcc(){
  case "$1" in
  "-pthread") return 0 ;;
  "-fopenmp") return 0 ;;
  *) return 1 ;;
  esac
}
ps(){ if ((verbosity>0));then printf "#";printf " '%s'" "$@";printf "\n";fi;"$@"; }
ex(){ # OUTFILE ERRFILE CMD [...]
  local O="$1" E="$2"; shift 2
  { { ps "$@" | tee -a "$O"; } 2>&1 1>&3 | tee -a "$E"; } 3>&1 1>&2
}
while (($#>0));do
  if forcc "$1";then
    ccargs+=",'$1'"
  else
    args+=("$1")
  fi
  shift
done
ex ccwrapper.{out,err} "$nvcc" "${args[@]}" -Xcompiler "${ccargs#,}"
